name: docker
on: [push]
jobs:
    build:
        name: docker
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository
              uses: actions/checkout@v3

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v2

            - name: Build and push Docker images
              uses: docker/build-push-action@v4
              with:
                  context: .
                  push: false

            - name: Build Docker images with Compose
              run: |
                  docker-compose build

            - name: Run container with Compose
              run: |
                  docker-compose up -d
                  sleep 10  # Give the server some time to start

            - name: Health check
              run: |
                  curl -f http://localhost:5000/health
